version: "3.7"
networks:
  app-tier:
    driver: bridge
services:
  db:
    container_name: ${NAMESPACE}_db
    image: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASSWD}
    networks:
      - app-tier
  redis:
    container_name: ${NAMESPACE}_redis
    image: 'redis'
    networks:
      - app-tier
  web:
    tty: true
    stdin_open: true
    container_name: ${NAMESPACE}_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/work
    working_dir: /work
    command: "bash scripts/docker/startup.sh"
    ports:
      - 3000:3000
    networks:
      - app-tier
  worker:
    tty: true
    stdin_open: true
    container_name: ${NAMESPACE}_worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/work
    working_dir: /work
    command: "bash scripts/docker/worker.sh"
    networks:
      - app-tier